# Generated by Django 3.1.4 on 2021-01-15 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cityinformation',
            name='city',
        ),
        migrations.AddField(
            model_name='placestovisit',
            name='closing_timming',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='placestovisit',
            name='opening_timming',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
