# Generated by Django 3.1.4 on 2021-01-27 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informations', '0002_auto_20210115_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cityinformation',
            name='description',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='hotelorrestaurantsinformation',
            name='description',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='placestovisit',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
