# Generated by Django 3.1.4 on 2021-01-15 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinalCharges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=120)),
                ('paid', models.BooleanField(default=False)),
                ('service_charges', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('food_charges', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('charges', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
    ]
