# Generated by Django 3.1.4 on 2021-01-13 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=120)),
                ('item_description', models.CharField(max_length=500)),
                ('item_image', models.FileField(upload_to='')),
                ('item_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('item_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.foodtype')),
            ],
        ),
    ]
