# Generated by Django 3.1.4 on 2021-01-14 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_fooditemorders_foodtotal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditemorders',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='foodtotal',
            name='food_items',
            field=models.ManyToManyField(blank=True, to='food.FoodItemOrders'),
        ),
    ]
