# Generated by Django 3.1.4 on 2021-01-25 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_auto_20210125_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='item_image',
            field=models.FileField(blank=True, null=True, upload_to='food item images/'),
        ),
    ]
