# Generated by Django 3.1.4 on 2021-01-23 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxibooking',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
